# Use official Python base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy files into container
COPY . .

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt
RUN apt-get update && apt-get install -y curl

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["python", "app.py"]
